---
- name: Install Java and Net-tools
  hosts: webserver1
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt:  name=openjdk-8-jre-headless
    - name: Install Net-tools
      apt:  name=net-tools

- name: Download and Unpack Nexus Installer
  hosts: webserver1
  become: yes
  tasks:
    - name: Check if Nexus folder exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar/Unpack Nexus
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find Nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{stat_result.stat.exists}}
    - name: Rename Nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Make Nexus user owner of Nexus-Sonatype Folders
  hosts: webserver1
  become: yes
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: Make nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start Nexus with Nexus user
  hosts: webserver1
  become: yes
  become_user: nexus
  tasks:
    - name: Set run_as_user Nexus
      lineinfile:             #Use blockinfile module for typing in multiple lines
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Check Nexus status with ps and netstat
  hosts: webserver1
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus 
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait 1 minute
      pause:
        minutes: 1
    - name: Check witn netstat
      shell: netstat -lnpt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}