---
- name: Install Docker and Docker-Compose
  hosts: webserver2
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Ensuring Docker and Docker-Compose Plugin is installed
      apt:
        pkg:
          - docker.io
          - docker-compose-v2
        state: present

- name: Start Docker daemon
  hosts: webserver2
  become: yes
  tasks:
    - name: Ensuring docker daemon is running
      systemd:
        name: docker
        state: started

- name: Add user to docker group
  hosts: webserver2
  become: yes
  tasks:
    - name: Adding user to docker group 
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Resetting the connection to server
      meta: reset_connection

- name: Start docker containers
  hosts: webserver2
  vars_files:
  - vault.yaml
  tasks:
    - name: Copy docker compose file
      copy:
        src: /mnt/c/Users/mohib/Ansible/docker-compose.yaml
        dest: /home/azureuser/docker-compose.yaml

    - name: Login into docker hub
      docker_login:
        registry_url: https://registry-1.docker.io/
        username: mohibshaikh
        password: "{{docker_password}}"

    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/azureuser
        state: present