version : '3.8'
services:
  java-maven-app:
    image: mohibshaikh/mohib-repo:1.1.82-77
    ports:
      - "8080:8080"
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=21fd4466
