---
- name: Configure nginx web server
  hosts: webserver
  become: yes  # This ensures tasks run with sudo privileges
  tasks: 
  - name: update apt cache
    apt:
      update_cache: yes
  - name: uninstall nginx server
    apt:
      name: nginx=1.18*
      state: absent
  - name: stop nginx server
    service:
      name: nginx
      state: stopped
  