- name: Copy docker compose file
  copy:
    src: docker-compose.yaml
    dest: /home/{{ user_name }}/docker-compose.yaml

- name: Login into docker hub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Start containers from compose
  community.docker.docker_compose_v2:
    project_src: /home/{{ user_name }}